documentation:
  - changed-files:
      - any-glob-to-any-file: docs/**
enhancement:
  - changed-files:
      - any-glob-to-any-file: src/**
tests:
  - changed-files:
      - any-glob-to-any-file: tests/**
