name: Generate Markdown Help

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/generate-help.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/generate-help.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install platyPS
        shell: pwsh
        run: |
          Install-Module platyPS -Force -Scope CurrentUser
      - name: Generate Markdown help
        shell: pwsh
        run: |
          $modules = Get-ChildItem -Path ./src -Directory
          foreach ($module in $modules) {
            $modulePath = Join-Path $module.FullName "$($module.Name).psd1"
            $imported = Import-Module -Name $modulePath -Force -PassThru
            $outputFolder = Join-Path './docs' $module.Name
            if (Test-Path $outputFolder) {
              Update-MarkdownHelp -Path $outputFolder -Force
            } else {
              New-MarkdownHelp -OutputFolder $outputFolder -Module $imported
            }
            Remove-Module $imported.Name
          }
      - name: Pull latest changes
        run: git pull --rebase origin ${{ github.ref_name }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update markdown help
          branch: ${{ github.ref_name }}
          file_pattern: docs/**
