name: Pester Tests

on:
  push:
    paths:
      - '**/*.ps1'
      - 'tests/**'
      - '.github/workflows/pester-tests.yml'
  pull_request:
    paths:
      - '**/*.ps1'
      - 'tests/**'
      - '.github/workflows/pester-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          modules-to-cache: Pester
      - name: Run Pester tests
        shell: pwsh
        run: |
          $cfg = Import-PowerShellDataFile ./PesterConfiguration.psd1
          Invoke-Pester -Configuration $cfg -CI
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
