name: Pester Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -Force -Scope CurrentUser -MinimumVersion 5.0.0 -ErrorAction Stop
      - name: Run Pester
        shell: pwsh
        run: Invoke-Pester -Path ./tests -Output Detailed
