name: Pester Tests

on:
  push:
    paths:
      - '**/*.ps1'
      - 'tests/**'
      - '.github/workflows/pester-tests.yml'
  pull_request:
    paths:
      - '**/*.ps1'
      - 'tests/**'
      - '.github/workflows/pester-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          modules-to-cache: Pester
      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester -Configuration (Import-PowerShellDataFile ./PesterConfiguration.psd1)
      - name: Ensure all functions have tests
        shell: pwsh
        run: |
          ./scripts/Ensure-TestCoverage.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
