name: PowerShell Lint

on:
  push:
    paths:
      - '**/*.ps1'
      - '.github/workflows/psscriptanalyzer.yml'
  pull_request:
    paths:
      - '**/*.ps1'
      - '.github/workflows/psscriptanalyzer.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
      - name: Install SARIF conversion module
        shell: pwsh
        run: |
          Install-Module ConvertToSARIF -Force -Scope CurrentUser
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Import-Module PSScriptAnalyzer
          Import-Module ConvertToSARIF
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning,Error |
            ConvertTo-SARIF -FilePath PSScriptAnalyzerResults.sarif
      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: PSScriptAnalyzerResults
          path: PSScriptAnalyzerResults.sarif
