name: PowerShell Lint

on:
  push:
    paths:
      - '**/*.ps1'
      - '.github/workflows/psscriptanalyzer.yml'
  pull_request:
    paths:
      - '**/*.ps1'
      - '.github/workflows/psscriptanalyzer.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          modules-to-cache: PSScriptAnalyzer, ConvertToSARIF
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Import-Module PSScriptAnalyzer
          Import-Module ConvertToSARIF
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning,Error |
            ConvertTo-SARIF -FilePath PSScriptAnalyzerResults.sarif
      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: PSScriptAnalyzerResults
          path: PSScriptAnalyzerResults.sarif
